### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by nrutledge** [mlabs-haskell/cardanow#39]
We have not put a lot of thought into error handling at this point. We need to ensure the following:

1. If any step fails (e.g., upload to R2), there is a retry mechanism in place.
2. If things continue to fail after a certain number of retries, we are alerted of the failure.
3. Someone running the snapshot service locally can also receive alerts on failures.

_This issue was brought up during the 2024/03/04 sync meeting._

**Comment by albertodvp** [comment]
Depends on #76.

Ideally we want to use pushgateway and notify when steps are correctly completed in the pipeline. Alerting can be then defined on prometheus

**Comment by albertodvp** [comment]
### Snapshot Creation Job:
1. At the start
2. After Mithril snapshot is downloaded
3. Before starting the TS application
4. After TS application is completed

### Upload Job:
1. Before upload starts
2. After upload is finished
